name: 'Send email at push'
description: 'Send email at push with some information about the other Github Actions jobs'

inputs:
  destination:
    description: 'Destination email'
    required: true
    default: 'marctorresmartinez@gmail.com'

  # syntax_check_job:
  #   description: 'First job status'
  #   required: true
    # default: 'undefined'

  test_execution_job:
    description: 'Second job status'
    required: true
    default: 'undefined'

  # build_statics_job:
  #   description: 'Third job status'
  #   required: true
  #   default: 'undefined'

  # deploy_job:
  #   description: 'Fourth job status'
  #   required: true
  #   default: 'undefined'

runs:
  using: 'node12'
  main: 'dist/index.js'